on:
  workflow_dispatch: {}
  pull_request:
    branches:
    - main
    - master
  push:
    branches:
    - main
    - master
name: Deployment
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
    - uses: actions/checkout@v4
    - run: semgrep ci

  gh-pages:
    runs-on: ubuntu-latest
    needs: semgrep
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies & build
      run: |
        npm ci
        npm run build

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_dir: ./build

  zap:
    name: OWASP ZAP Baseline Scan
    needs: gh-pages
    env:
      REPO_NAME: ${{ github.event.repository.name }}
    runs-on: ubuntu-latest
    steps:
    - name: Download OWASP ZAP Docker image
      run: docker pull zaproxy/zap-stable

    - name: Run ZAP Baseline Scan against Vercel URL
      run: |
        # generate a unique report name using the current epoch seconds
        TIMESTAMP=$(date +%s)
        REPORT_NAME="zap-report-${TIMESTAMP}.html"
        echo "Report will be saved as: $REPORT_NAME"

        TARGET_URL="https://$REPO_NAME"
        echo "Scanning target: $TARGET_URL"

        # ensure the output directory exists
        mkdir -p "$HOME/zap-reports"
        echo "Report directory: $HOME/zap-reports"

        # run ZAP baseline scan, outputting to the dynamic filename
        docker run --rm \
          --user root \
          -v "$HOME/zap-reports":/zap/wrk \
          zaproxy/zap-stable \
          zap-baseline.py \
          -t "$TARGET_URL" \
          -r "$REPORT_NAME" \
          -I

        # expose the report name for the next step
        echo "REPORT_NAME=${REPORT_NAME}" >> $GITHUB_ENV
        echo "REPORT_LOCATION=$HOME/zap-reports" >> $GITHUB_ENV

    - name: Show which report we'll upload
      run: |
        echo "Uploading report: ${{ env.REPORT_NAME }}"

    - name: Upload ZAP HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: zap-report
        path: ${{ env.REPORT_LOCATION }}/${{ env.REPORT_NAME }}
